### PR TITLE
Update package.js -> not official package

### PR DESCRIPTION
**Pull request by nolimits4web**
Don't confuse users, it is not official and a bit outdated. The official package is https://atmospherejs.com/nolimits4web/swiper

### CODE REVIEW

**Comment by zimme** [comment]
If there's an official package out there we'll just talk with the maintainers of the lib and see if they want this namespace or the one they're using and then we just `api.use` and `api.imply` the package which "survives" from from the "dying" package and mark it as removed

**Comment by nolimits4web** [comment]
I am the maintainer of original lib and official package. I'm fine with the namespace i have, just asking to remove the "official" word from package description, because again, it confuses users

**Comment by zimme** [comment]
I don't see the need for this package if you have an official one. I'll just have a look that the api is the same on this one and yours and if that's the case I'll just have this package use yours and "remove" this one. otherwise I'll just have this marked as deprecated and remove the "official" tag

**Comment by nolimits4web** [comment]
Ok, thanks

**Comment by splendido** [comment]
The only difference seems to be `swiper:swiper` adds `Swiper` as a global export while the *original* one keeps `window.Swiper`.
This is not properly the *meteoric* way, but I'd have no problem in removing this package from Atmosphere.
...also, at the moment, the one with the most downloads is [lacosta:swiper](https://atmospherejs.com/lacosta/swiper) which also exports `Swiper` as a global var.

Btw, I'm also a MOD on atmosphere and we might flag all *unofficial* packages now that we have THE official one!

**Comment by skifaster** [comment]
As the original publisher of swiper:swiper, i'm happy to transfer this to someone who wants to maintain an official package. or it can be flagged, whatever is helpful.

**Pull request closed without merging**
